### PR TITLE
Add wanyufe as owner and maintainer

### PR DESCRIPTION
**Pull request by wanyufe**
*Issue #, if available:*
Add wanyufe as owner and maintainer due to team member changes.
*Description of changes:*
Add wanyufe as owner and maintainer
*Testing performed:*
c/a

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by maxdrib — APPROVED** [review]

**Comment by maxdrib** [comment]
I left a comment in https://github.com/kubernetes/org/issues/3846 asking mrbobbytales to take a look to see what the issue is

**Comment by rohityadavcloud** [comment]
@wanyufe have you accepted the invite to be added to the k8s-sig Github org?

**Review by davidjumani — APPROVED** [review]

**Comment by chrisdoherty4** [comment]
@wanyufe is this PR still relevant?

**Comment by rohityadavcloud** [comment]
ping @wanyufe cc @jweite-amazon @chrisdoherty4

**Comment by chrisdoherty4** [comment]
I think we can close this PR now.

**Pull request closed without merging**
