### PR TITLE
E2e increase wait time

### PR DESCRIPTION
**Pull request by vishesh92**
*Issue #, if available:*
Tests fail intermittently because the cluster/control plane is not ready or the service is not ready for deployment
*Description of changes:*
Increase wait time & retries
*Testing performed:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -i rockylinux-8-kube -k 1.26.5

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -i rockylinux-8-kube -k 1.25.10 -f 1.25.10 -t 1.26.5

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -k 1.25.10 -f 1.25.10 -t 1.26.5

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -k 1.25.10 -f 1.25.10 -t 1.26.5

**Comment by weizhouapache** [comment]
@vishesh92 
it seems there is no obvious improvement on the testing results.
can we close this PR ?

**Comment by vishesh92** [comment]
> @vishesh92 
> it seems there is no obvious improvement on the testing results.
> can we close this PR ?

Yeah. Let's close this.

**Pull request closed without merging**
