### PR TITLE
Upgrade direct dependencies

### PR DESCRIPTION
**Pull request by hrak**
*Issue #, if available:*

*Description of changes:*

This PR upgrades most direct dependencies to their latest versions. I stayed within k8s 1.25 for the k8s deps.

*Testing performed:*

build successful & tests pass

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hrak** [comment]
Updated for k8s v1.25.13. Can this be  merged? There is not much exciting change here.

**Comment by vishesh92** [comment]
@hrak Just started e2e test runs. Let's merge it once they are complete.

**Comment by hrak** [comment]
> Test Results : (tid-329) Environment: kvm Rocky8(x3), Advanced Networking with Management Server Rocky8 Kubernetes Version: v1.27.2 Kubernetes Version upgrade from: v1.26.5 Kubernetes Version upgrade to: v1.27.2 CloudStack Version: 4.17 Template: ubuntu-2004-kube E2E Test Run Logs: https://github.com/blueorangutan/capc-prs/releases/download/capc-pr-ci-cd/capc-e2e-artifacts-pr297-sl-329.zip
> 
> ```
> Summarizing 1 Failure:
> 
> [Fail] When testing affinity group [It] Should have host affinity group when affinity is pro 
> /jenkins/workspace/capc-e2e-new/test/e2e/common.go:331
> 
> ```

I'm going to need some help with this test failure. I'm not entirely sure it is related to the changes.

```
[32m• [SLOW TEST:432.775 seconds][0m
When testing multiple CPs in a shared network with kubevip
[90m/jenkins/workspace/capc-e2e-new/test/e2e/shared_network_kubevip_test.go:27[0m
  Should successfully create a cluster with multiple CPs in a shared network
  [90m/jenkins/workspace/capc-e2e-new/test/e2e/shared_network_kubevip.go:59[0m
[90m------------------------------[0m
[0mWhen testing affinity group[0m 
  [1mShould have host affinity group when affinity is pro[0m
  [37m/jenkins/workspace/capc-e2e-new/test/e2e/affinity_group.go:68[0m
[1mSTEP[0m: Getting a CloudStack client secret
[1mSTEP[0m: Creating a CloudStack client
[1mSTEP[0m: Creating a namespace for hosting the "affinity-group" test spec
INFO: Creating namespace affinity-group-5cb2u3
INFO: Creating event watcher for namespace "affinity-group-5cb2u3"
INFO: Creating the workload cluster with name "affinity-group-fm0sv5" using the "affinity-group-pro" template (Kubernetes v1.27.2, 3 control-plane machines, 2 worker machines)
INFO: Getting the cluster template yaml
INFO: clusterctl config cluster affinity-group-fm0sv5 --infrastructure (default) --kubernetes-version v1.27.2 --control-plane-machine-count 3 --worker-machine-count 2 --flavor affinity-group-pro
INFO: Applying the cluster template yaml to the cluster
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/affinity-group-fm0sv5-md-0 created
cluster.cluster.x-k8s.io/affinity-group-fm0sv5 created
machinedeployment.cluster.x-k8s.io/affinity-group-fm0sv5-md-0 created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/affinity-group-fm0sv5-control-plane created
cloudstackcluster.infrastructure.cluster.x-k8s.io/affinity-group-fm0sv5 created
cloudstackmachinetemplate.infrastructure.cluster.x-k8s.io/affinity-group-fm0sv5-control-plane created
cloudstackmachinetemplate.infrastructure.cluster.x-k8s.io/affinity-group-fm0sv5-md-0 created

INFO: Waiting for the cluster infrastructure to be provisioned
[1mSTEP[0m: Waiting for cluster to enter the provisioned phase
INFO: Waiting for control plane to be initialized
INFO: Waiting for the first control plane machine managed by affinity-group-5cb2u3/affinity-group-fm0sv5-control-plane to be provisioned
[1mSTEP[0m: Waiting for one control plane node to exist
INFO: Installing a CNI plugin to the workload cluster
clusterrole.rbac.authorization.k8s.io/kindnet created
clusterrolebinding.rbac.authorization.k8s.io/kindnet created
serviceaccount/kindnet created
daemonset.apps/kindnet created

INFO: Waiting for control plane to be ready
INFO: Waiting for the remaining control plane machines managed by affinity-group-5cb2u3/affinity-group-fm0sv5-control-plane to be provisioned
[1mSTEP[0m: Waiting for all control plane nodes to exist
INFO: Waiting for control plane affinity-group-5cb2u3/affinity-group-fm0sv5-control-plane to be ready (implies underlying nodes to be ready as well)
[1mSTEP[0m: Waiting for the control plane to be ready
[1mSTEP[0m: Checking all the the control plane machines are in the expected failure domains
INFO: Waiting for the machine deployments to be provisioned
[1mSTEP[0m: Waiting for the workload nodes to exist
[1mSTEP[0m: Checking all the machines controlled by affinity-group-fm0sv5-md-0 are in the "<None>" failure domain
INFO: Waiting for the machine pools to be provisioned
[1mSTEP[0m: Getting a CloudStack client secret
[1mSTEP[0m: Creating a CloudStack client
[1mSTEP[0m: Listing all machines
[1mSTEP[0m: affinity-group-fm0sv5-control-plane-jstr9 is in host ref-trl-5533-k-M7-remoteRequest-kvm1 (429a9e48-241d-413d-8095-9ba7954d9779)
[1mSTEP[0m: affinity-group-fm0sv5-control-plane-br7fn is in host ref-trl-5533-k-M7-remoteRequest-kvm1 (429a9e48-241d-413d-8095-9ba7954d9779)
[1mSTEP[0m: affinity-group-fm0sv5-md-0-9ph8l is in host ref-trl-5533-k-M7-remoteRequest-kvm3 (580e782c-480e-4f20-832f-d7c18312b8b4)
[1mSTEP[0m: affinity-group-fm0sv5-md-0-5fjh7 is in host ref-trl-5533-k-M7-remoteRequest-kvm2 (f48baeea-caaf-4e8b-b255-cef5f435f793)
[1mSTEP[0m: Dumping logs from the "affinity-group-fm0sv5" workload cluster
Failed to get logs for machine affinity-group-fm0sv5-control-plane-ffrlf, cluster affinity-group-5cb2u3/affinity-group-fm0sv5: error creating container exec: Error response from daemon: No such container: affinity-group-fm0sv5-control-plane-ffrlf
Failed to get logs for machine affinity-group-fm0sv5-control-plane-hb8s2, cluster affinity-group-5cb2u3/affinity-group-fm0sv5: error creating container exec: Error response from daemon: No such container: affinity-group-fm0sv5-control-plane-hb8s2
Failed to get logs for machine affinity-group-fm0sv5-control-plane-zgzhd, cluster affinity-group-5cb2u3/affinity-group-fm0sv5: error creating container exec: Error response from daemon: No such container: affinity-group-fm0sv5-control-plane-zgzhd
Failed to get logs for machine affinity-group-fm0sv5-md-0-5c9c997966-gnht5, cluster affinity-group-5cb2u3/affinity-group-fm0sv5: error creating container exec: Error response from daemon: No such container: affinity-group-fm0sv5-md-0-5c9c997966-gnht5
Failed to get logs for machine affinity-group-fm0sv5-md-0-5c9c997966-hrpkd, cluster affinity-group-5cb2u3/affinity-group-fm0sv5: error creating container exec: Error response from daemon: No such container: affinity-group-fm0sv5-md-0-5c9c997966-hrpkd
[1mSTEP[0m: Dumping all the Cluster API resources in the "affinity-group-5cb2u3" namespace
[1mSTEP[0m: Deleting cluster affinity-group-5cb2u3/affinity-group-fm0sv5
[1mSTEP[0m: Deleting cluster affinity-group-fm0sv5
INFO: Waiting for the Cluster affinity-group-5cb2u3/affinity-group-fm0sv5 to be deleted
[1mSTEP[0m: Waiting for cluster affinity-group-fm0sv5 to be deleted
[1mSTEP[0m: Deleting namespace used for hosting the "affinity-group" test spec
INFO: Deleting namespace affinity-group-5cb2u3
[1mSTEP[0m: Getting a CloudStack client secret
[1mSTEP[0m: Creating a CloudStack client

[91m[1m• Failure [343.292 seconds][0m
When testing affinity group
[90m/jenkins/workspace/capc-e2e-new/test/e2e/affinity_group_test.go:27[0m
  [91m[1mShould have host affinity group when affinity is pro [It][0m
  [90m/jenkins/workspace/capc-e2e-new/test/e2e/affinity_group.go:68[0m

  [91maffinity-group-fm0sv5-md-0-5fjh7 is deployed in a different host: ref-trl-5533-k-M7-remoteRequest-kvm2 when affinity type is pro[0m

  /jenkins/workspace/capc-e2e-new/test/e2e/common.go:331

  [91mFull Stack Trace[0m
  sigs.k8s.io/cluster-api-provider-cloudstack-staging/test/e2e.CheckAffinityGroup(0xc00058c500, {0xc0010123a8, 0x15}, {0x2654374, 0x3})
  	/jenkins/workspace/capc-e2e-new/test/e2e/common.go:331 +0x4e5
  sigs.k8s.io/cluster-api-provider-cloudstack-staging/test/e2e.executeTest({0x29f9d20, 0xc000058148}, {0xc000d66a50, {0xc000648afb, 0x4c}, {0x2a08a08, 0xc000abd8c0}, {0xc000648a90, 0x2a}, 0x0, ...}, ...)
  	/jenkins/workspace/capc-e2e-new/test/e2e/affinity_group.go:111 +0x60e
  sigs.k8s.io/cluster-api-provider-cloudstack-staging/test/e2e.AffinityGroupSpec.func2()
  	/jenkins/workspace/capc-e2e-new/test/e2e/affinity_group.go:69 +0x97
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0x0?)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xb1
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc00019b860?)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x125
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0x48?)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/it_node.go:26 +0x7b
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc00063e690, 0xc000c2b9f0?, {0x29db980, 0xc0000aa900})
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:215 +0x2a9
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc00063e690, {0x29db980, 0xc0000aa900})
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:138 +0xf2
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0002d4b00, 0xc00063e690)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:200 +0xf1
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0002d4b00)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:170 +0x1b6
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0002d4b00)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:66 +0xc5
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc000184c40, {0x7f877a71eaa8, 0xc00019b6c0}, {0x265b87d, 0x8}, {0xc000131040, 0x2, 0x2}, {0x29fbbc0, 0xc0000aa900}, ...)
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x4e5
  github.com/onsi/ginkgo.runSpecsWithCustomReporters({0x29de6a0?, 0xc00019b6c0}, {0x265b87d, 0x8}, {0xc000131020, 0x2, 0x267d76e?})
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x189
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters({0x29de6a0, 0xc00019b6c0}, {0x265b87d, 0x8}, {0xc000093f50, 0x1, 0x1})
  	/root/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:228 +0x1be
  sigs.k8s.io/cluster-api-provider-cloudstack-staging/test/e2e.TestE2E(0x2779540?)
  	/jenkins/workspace/capc-e2e-new/test/e2e/e2e_suite_test.go:100 +0xba
  testing.tRunner(0xc00019b6c0, 0x277ce18)
  	/usr/local/go/src/testing/testing.go:1446 +0x10b
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:1493 +0x35f
```

**Comment by vishesh92** [comment]
@hrak The failure is an intermittent one. Have seen that test fail sometimes on other PRs as well.

**Review by vishesh92 — APPROVED** [review]

**Pull request merged**
