### PR TITLE
[DO NOT MERGE] main: Health Check

### PR DESCRIPTION
**Pull request by weizhouapache**
*Issue #, if available:*

*Description of changes:*

*Testing performed:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan help

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -h xen -k 1.24.14

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -h xen -k 1.25.10

**Comment by weizhouapache** [comment]
/run-e2e -c 4.18 -h xen -k 1.23.3 -f 1.23.3 -t 1.24.14

**Comment by weizhouapache** [comment]
/run-e2e -k 1.27.2 -c 4.18 -i rockylinux-8-kube

**Comment by vishesh92** [comment]
/run-e2e -k 1.27.2 -c 4.18 -i rockylinux-8-kube

**Comment by vishesh92** [comment]
Ignore ^. I cancelled the test run.

**Comment by rohityadavcloud** [comment]
@vishesh92 @weizhouapache not urgent - still worth checking, why e2e is (a) taking time, (b) probably failing for some reason at backend CI/CD?

**Comment by rohityadavcloud** [comment]
cc @g-gaston @weizhouapache @vishesh92 @hrak we found our Github bot blueorangutan was subject to Github rate limits, which is why it could in some cases run tests and couldn't respond to Github; we'll investigate e2e tests pipeline in coming days/week; if it's super urgent pl advice.

**Comment by rohityadavcloud** [comment]
cc @vignesh-goutham @g-gaston @hrak if it helps - pl kick the tests yourself, we've found the Github rate limits on the bot account to be an issue. If you think there's an issue with e2d infra let us (@weizhouapache @vishesh92 @rohityadavcloud) know on your PRs.

**Comment by rohityadavcloud** [comment]
Just FYI @g-gaston - it seems a smoketest run takes b/w 3-4hrs, I see some intermittent failures which I'm not sure if it's due to actual issues or just CI/CD flakiness (cc @weizhouapache @vishesh92 to review soon). Let me rekick them to see if they consistently fail.

/run-e2e -c 4.18

**Pull request closed without merging**
