### PR TITLE
OWNERS: update per repo migration issue

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Refer to https://github.com/kubernetes/org/issues/3279, to facilitate repo migration we can start with a limited set of owners that we can grow over time post-migration. I've raised this issue with the org https://github.com/kubernetes/org/issues/3312

### CODE REVIEW

**Comment by davidjumani** [comment]
Raised an issue for me as well
https://github.com/kubernetes/org/issues/3319

**Comment by davidjumani** [comment]
Guessing this will need to be approved by someone here https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/main/OWNERS
@pmotyka @maxdrib @vignesh-goutham @jweite-amazon @mrog @rejoshed @wongni

**Review by pmotyka — APPROVED** [review]

**Pull request merged**
