### PR TITLE
Fixup ginkgo targets.

### PR DESCRIPTION
**Pull request by rejoshed**
*Issue #, if available:* N/A

*Description of changes:*
Noticed that test requirements for ginkgo didn't work because the test target needs ginkgo_v2.

Since in the end bin/ginkgo doesn't actually exist anymore, I made it a phony target that builds both versions.

*Testing performed:*
`checkout branch && rm -rf ./bin && make test`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by maxdrib — APPROVED** [review]
Thanks for patching this issue

**Comment by maxdrib** [comment]
> @rejoshed: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> capi-provider-cloudstack-presubmit-unit-test	[4d0a308](https://github.com/aws/cluster-api-provider-cloudstack/commit/4d0a3082dc0b9b0708cb9151434a086c90846677)	[link](https://beta.prow.model-rocket.aws.dev/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-a8z3fg9jrzai/pr-logs/pull/aws_cluster-api-provider-cloudstack/95/capi-provider-cloudstack-presubmit-unit-test/1526601349179904000)	true	`/test capi-provider-cloudstack-presubmit-unit-test`
> [Full PR test history](https://beta.prow.model-rocket.aws.dev/pr-history?org=aws&repo=cluster-api-provider-cloudstack&pr=95). [Your PR dashboard](https://beta.prow.model-rocket.aws.dev/pr?query=is:pr+state:open+author:rejoshed).

I think we may want to try increasing the timeout that was recently added on the envtests from 1 minute to 5 minutes. How would you feel about testing that change @rejoshed ?

**Comment by rejoshed** [comment]
check-cla

**Pull request closed without merging**
