### PR TITLE
Readding self as approver for CAPC repo

### PR DESCRIPTION
**Pull request by maxdrib**
*Issue #, if available:*

*Description of changes:*
Now that the repo is migrated and I've joined the kubernetes-sigs org, I'd like to re-add myself as an owner to this repository so that we can continue to iterate quickly

*Testing performed:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by maxdrib** [comment]
Requested membership https://github.com/kubernetes/org/issues/3466

**Comment by davidjumani** [comment]
@maxdrib Can update the Readme with yourself as the maintainer / reviewer

**Pull request merged**
